use std::mem;
use wgpu;

// ── Plain rect vertex (used by the tessellation pipeline) ──────────────────

#[repr(C)]
#[derive(Copy, Clone, Debug, bytemuck::Pod, bytemuck::Zeroable)]
struct Vertex {
    position: [f32; 2],
    color: [f32; 4],
}

// ── Per-instance data for the SDF rounded-rect pipeline ───────────────────
//
// Each rounded rect is a single quad (6 vertices, generated by vertex shader
// from vertex_index 0-5).  All shape parameters are instance fields.
//
// @location bindings (must match rounded_rect.wgsl):
//   0  pos_size     – [x, y, w, h]  screen pixels, top-left origin
//   1  radii        – [corner_radius, border_width, screen_w, screen_h]
//   2  fill_color   – [r, g, b, a]
//   3  border_color – [r, g, b, a]

#[repr(C)]
#[derive(Copy, Clone, Debug, bytemuck::Pod, bytemuck::Zeroable)]
struct RoundedRectInstance {
    pos_size: [f32; 4],
    radii: [f32; 4],
    fill_color: [f32; 4],
    border_color: [f32; 4],
}

pub struct ShapeRenderer {
    // tessellation pipeline (plain rects, circles)
    pipeline: wgpu::RenderPipeline,
    vertex_buffer: wgpu::Buffer,
    vertices: Vec<Vertex>,
    vertex_capacity: usize,

    // sdf pipeline (rounded rects)
    sdf_pipeline: wgpu::RenderPipeline,
    instance_buffer: wgpu::Buffer,
    instances: Vec<RoundedRectInstance>,
    instance_capacity: usize,

    screen_width: f32,
    screen_height: f32,
    ndc_scale_x: f32,
    ndc_scale_y: f32,
}

impl ShapeRenderer {
    pub fn new(
        device: &wgpu::Device,
        format: wgpu::TextureFormat,
        width: f32,
        height: f32,
    ) -> Self {
        // ── tessellation pipeline ─────────────────────────────────────────
        let tess_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Shape Shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("../../shaders/shape.wgsl").into()),
        });

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Shape Pipeline"),
            layout: None,
            vertex: wgpu::VertexState {
                module: &tess_shader,
                entry_point: Some("vs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                buffers: &[wgpu::VertexBufferLayout {
                    array_stride: mem::size_of::<Vertex>() as wgpu::BufferAddress,
                    step_mode: wgpu::VertexStepMode::Vertex,
                    attributes: &[
                        wgpu::VertexAttribute {
                            offset: 0,
                            shader_location: 0,
                            format: wgpu::VertexFormat::Float32x2,
                        },
                        wgpu::VertexAttribute {
                            offset: 8,
                            shader_location: 1,
                            format: wgpu::VertexFormat::Float32x4,
                        },
                    ],
                }],
            },
            fragment: Some(wgpu::FragmentState {
                module: &tess_shader,
                entry_point: Some("fs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                targets: &[Some(wgpu::ColorTargetState {
                    format,
                    blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                ..Default::default()
            },
            depth_stencil: None,
            multisample: wgpu::MultisampleState {
                count: 4,
                mask: !0,
                alpha_to_coverage_enabled: false,
            },
            multiview: None,
            cache: None,
        });

        let vertex_capacity = 4096;
        let vertex_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Shape Vertex Buffer"),
            size: (vertex_capacity * mem::size_of::<Vertex>()) as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        // sdf pipeline 
        let sdf_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("SDF Rounded Rect Shader"),
            source: wgpu::ShaderSource::Wgsl(
                include_str!("../../shaders/rounded_rect.wgsl").into(),
            ),
        });

        let sdf_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("SDF Rounded Rect Pipeline"),
            layout: None,
            vertex: wgpu::VertexState {
                module: &sdf_shader,
                entry_point: Some("vs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                buffers: &[wgpu::VertexBufferLayout {
                    array_stride: mem::size_of::<RoundedRectInstance>() as wgpu::BufferAddress,
                    step_mode: wgpu::VertexStepMode::Instance,
                    attributes: &[
                        wgpu::VertexAttribute {
                            offset: 0,
                            shader_location: 0,
                            format: wgpu::VertexFormat::Float32x4,
                        },
                        wgpu::VertexAttribute {
                            offset: 16,
                            shader_location: 1,
                            format: wgpu::VertexFormat::Float32x4,
                        },
                        wgpu::VertexAttribute {
                            offset: 32,
                            shader_location: 2,
                            format: wgpu::VertexFormat::Float32x4,
                        },
                        wgpu::VertexAttribute {
                            offset: 48,
                            shader_location: 3,
                            format: wgpu::VertexFormat::Float32x4,
                        },
                    ],
                }],
            },
            fragment: Some(wgpu::FragmentState {
                module: &sdf_shader,
                entry_point: Some("fs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                targets: &[Some(wgpu::ColorTargetState {
                    format,
                    blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                ..Default::default()
            },
            depth_stencil: None,
            multisample: wgpu::MultisampleState {
                count: 4,
                mask: !0,
                alpha_to_coverage_enabled: false,
            },
            multiview: None,
            cache: None,
        });

        let instance_capacity = 512;
        let instance_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("SDF Instance Buffer"),
            size: (instance_capacity * mem::size_of::<RoundedRectInstance>()) as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        Self {
            pipeline,
            vertex_buffer,
            vertices: Vec::with_capacity(vertex_capacity),
            vertex_capacity,

            sdf_pipeline,
            instance_buffer,
            instances: Vec::with_capacity(instance_capacity),
            instance_capacity,

            screen_width: width,
            screen_height: height,
            ndc_scale_x: 2.0 / width,
            ndc_scale_y: 2.0 / height,
        }
    }

    #[inline(always)]
    pub fn clear(&mut self) {
        self.vertices.clear();
        self.instances.clear();
    }

    #[inline(always)]
    fn to_ndc(&self, x: f32, y: f32) -> [f32; 2] {
        [x * self.ndc_scale_x - 1.0, 1.0 - y * self.ndc_scale_y]
    }

    // tessellation helpers (plain rects, circles) 

    #[inline(always)]
    fn push_quad(
        &mut self,
        p1: [f32; 2],
        p2: [f32; 2],
        p3: [f32; 2],
        p4: [f32; 2],
        color: [f32; 4],
    ) {
        self.vertices.reserve(6);
        unsafe {
            let len = self.vertices.len();
            let ptr = self.vertices.as_mut_ptr().add(len);
            ptr.write(Vertex {
                position: p1,
                color,
            });
            ptr.add(1).write(Vertex {
                position: p2,
                color,
            });
            ptr.add(2).write(Vertex {
                position: p3,
                color,
            });
            ptr.add(3).write(Vertex {
                position: p2,
                color,
            });
            ptr.add(4).write(Vertex {
                position: p4,
                color,
            });
            ptr.add(5).write(Vertex {
                position: p3,
                color,
            });
            self.vertices.set_len(len + 6);
        }
    }

    pub fn rect(
        &mut self,
        x: f32,
        y: f32,
        w: f32,
        h: f32,
        color: [f32; 4],
        outline_color: [f32; 4],
        outline_thickness: f32,
    ) {
        let p1 = self.to_ndc(x, y);
        let p2 = self.to_ndc(x + w, y);
        let p3 = self.to_ndc(x, y + h);
        let p4 = self.to_ndc(x + w, y + h);
        self.push_quad(p1, p2, p3, p4, color);
        if outline_thickness > 0.0 {
            self.rect_outline_fast(x, y, w, h, outline_color, outline_thickness * 0.5);
        }
    }

    #[inline]
    fn rect_outline_fast(&mut self, x: f32, y: f32, w: f32, h: f32, color: [f32; 4], half: f32) {
        self.push_quad(
            self.to_ndc(x - half, y - half),
            self.to_ndc(x + w + half, y - half),
            self.to_ndc(x - half, y + half),
            self.to_ndc(x + w + half, y + half),
            color,
        );
        self.push_quad(
            self.to_ndc(x - half, y + h - half),
            self.to_ndc(x + w + half, y + h - half),
            self.to_ndc(x - half, y + h + half),
            self.to_ndc(x + w + half, y + h + half),
            color,
        );
        self.push_quad(
            self.to_ndc(x - half, y + half),
            self.to_ndc(x + half, y + half),
            self.to_ndc(x - half, y + h - half),
            self.to_ndc(x + half, y + h - half),
            color,
        );
        self.push_quad(
            self.to_ndc(x + w - half, y + half),
            self.to_ndc(x + w + half, y + half),
            self.to_ndc(x + w - half, y + h - half),
            self.to_ndc(x + w + half, y + h - half),
            color,
        );
    }

    #[inline(always)]
    pub fn draw_rect(
        &mut self,
        x: f32,
        y: f32,
        w: f32,
        h: f32,
        color: [f32; 4],
        outline_color: [f32; 4],
        outline_thickness: f32,
    ) {
        self.rect(x, y, w, h, color, outline_color, outline_thickness);
    }

    pub fn draw_rect_clipped(
        &mut self,
        x: f32,
        y: f32,
        w: f32,
        h: f32,
        color: [f32; 4],
        clip: [f32; 4],
    ) {
        let [cx, cy, cx2, cy2] = clip;
        let x1 = x.max(cx);
        let y1 = y.max(cy);
        let x2 = (x + w).min(cx2);
        let y2 = (y + h).min(cy2);
        if x2 <= x1 || y2 <= y1 {
            return;
        }
        let p1 = self.to_ndc(x1, y1);
        let p2 = self.to_ndc(x2, y1);
        let p3 = self.to_ndc(x1, y2);
        let p4 = self.to_ndc(x2, y2);
        self.push_quad(p1, p2, p3, p4, color);
    }

    fn circle(
        &mut self,
        cx: f32,
        cy: f32,
        radius: f32,
        color: [f32; 4],
        outline_color: [f32; 4],
        outline_thickness: f32,
    ) {
        const SEGMENTS: usize = 32;
        self.vertices.reserve(SEGMENTS * 3);
        let center = self.to_ndc(cx, cy);

        use std::sync::LazyLock;
        static CIRCLE_LUT: LazyLock<[(f32, f32); 33]> = LazyLock::new(|| {
            let mut lut = [(0.0f32, 0.0f32); 33];
            for i in 0..=32 {
                let angle = (i as f32 / 32.0) * 2.0 * std::f32::consts::PI;
                lut[i] = (angle.cos(), angle.sin());
            }
            lut
        });

        for i in 0..SEGMENTS {
            let (cos1, sin1) = CIRCLE_LUT[i];
            let (cos2, sin2) = CIRCLE_LUT[i + 1];
            let p1 = self.to_ndc(cx + radius * cos1, cy + radius * sin1);
            let p2 = self.to_ndc(cx + radius * cos2, cy + radius * sin2);
            unsafe {
                let len = self.vertices.len();
                let ptr = self.vertices.as_mut_ptr().add(len);
                ptr.write(Vertex {
                    position: center,
                    color,
                });
                ptr.add(1).write(Vertex {
                    position: p1,
                    color,
                });
                ptr.add(2).write(Vertex {
                    position: p2,
                    color,
                });
                self.vertices.set_len(len + 3);
            }
        }

        if outline_thickness > 0.0 {
            self.circle_outline_fast(cx, cy, radius, outline_color, outline_thickness);
        }
    }

    #[inline]
    fn circle_outline_fast(
        &mut self,
        cx: f32,
        cy: f32,
        radius: f32,
        color: [f32; 4],
        thickness: f32,
    ) {
        const SEGMENTS: usize = 32;
        let inner_radius = radius - thickness * 0.5;
        let outer_radius = radius + thickness * 0.5;
        self.vertices.reserve(SEGMENTS * 6);

        use std::sync::LazyLock;
        static CIRCLE_LUT: LazyLock<[(f32, f32); 33]> = LazyLock::new(|| {
            let mut lut = [(0.0f32, 0.0f32); 33];
            for i in 0..=32 {
                let angle = (i as f32 / 32.0) * 2.0 * std::f32::consts::PI;
                lut[i] = (angle.cos(), angle.sin());
            }
            lut
        });

        for i in 0..SEGMENTS {
            let (cos1, sin1) = CIRCLE_LUT[i];
            let (cos2, sin2) = CIRCLE_LUT[i + 1];
            let inner1 = self.to_ndc(cx + inner_radius * cos1, cy + inner_radius * sin1);
            let inner2 = self.to_ndc(cx + inner_radius * cos2, cy + inner_radius * sin2);
            let outer1 = self.to_ndc(cx + outer_radius * cos1, cy + outer_radius * sin1);
            let outer2 = self.to_ndc(cx + outer_radius * cos2, cy + outer_radius * sin2);
            self.push_quad(inner1, outer1, inner2, outer2, color);
        }
    }

    #[inline(always)]
    pub fn draw_circle(
        &mut self,
        cx: f32,
        cy: f32,
        radius: f32,
        color: [f32; 4],
        outline_color: [f32; 4],
        outline_thickness: f32,
    ) {
        self.circle(cx, cy, radius, color, outline_color, outline_thickness);
    }

    // sdf rounded rect 
    //
    // one instance per rounded rect.  the vertex shader expands it to a quad
    // covering the rect bounds (+ 1px bleed for aa).

    pub fn rounded_rect(
        &mut self,
        x: f32,
        y: f32,
        w: f32,
        h: f32,
        radius: f32,
        color: [f32; 4],
        outline_color: [f32; 4],
        outline_thickness: f32,
    ) {
        let radius = radius.min(w * 0.5).min(h * 0.5);
        self.instances.push(RoundedRectInstance {
            pos_size: [x, y, w, h],
            radii: [
                radius,
                outline_thickness,
                self.screen_width,
                self.screen_height,
            ],
            fill_color: color,
            border_color: outline_color,
        });
    }

    #[inline(always)]
    pub fn draw_rounded_rect(
        &mut self,
        x: f32,
        y: f32,
        w: f32,
        h: f32,
        radius: f32,
        color: [f32; 4],
        outline_color: [f32; 4],
        outline_thickness: f32,
    ) {
        self.rounded_rect(x, y, w, h, radius, color, outline_color, outline_thickness);
    }

    // render 

    pub fn render<'pass>(
        &'pass mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        pass: &mut wgpu::RenderPass<'pass>,
    ) {
        // tessellation draw (plain rects, circles)
        if !self.vertices.is_empty() {
            let vertex_data = bytemuck::cast_slice(&self.vertices);
            let required_size = vertex_data.len() as u64;

            if required_size > self.vertex_buffer.size() {
                let new_size = (required_size * 3 / 2).max(required_size);
                self.vertex_buffer = device.create_buffer(&wgpu::BufferDescriptor {
                    label: Some("Shape Vertex Buffer"),
                    size: new_size,
                    usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
                    mapped_at_creation: false,
                });
                self.vertex_capacity = (new_size / mem::size_of::<Vertex>() as u64) as usize;
            }

            queue.write_buffer(&self.vertex_buffer, 0, vertex_data);
            pass.set_pipeline(&self.pipeline);
            pass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
            pass.draw(0..self.vertices.len() as u32, 0..1);
        }

        // sdf draw (rounded rects)
        if !self.instances.is_empty() {
            let instance_data = bytemuck::cast_slice(&self.instances);
            let required_size = instance_data.len() as u64;

            if required_size > self.instance_buffer.size() {
                let new_size = (required_size * 3 / 2).max(required_size);
                self.instance_buffer = device.create_buffer(&wgpu::BufferDescriptor {
                    label: Some("SDF Instance Buffer"),
                    size: new_size,
                    usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
                    mapped_at_creation: false,
                });
                self.instance_capacity =
                    (new_size / mem::size_of::<RoundedRectInstance>() as u64) as usize;
            }

            queue.write_buffer(&self.instance_buffer, 0, instance_data);
            pass.set_pipeline(&self.sdf_pipeline);
            pass.set_vertex_buffer(0, self.instance_buffer.slice(..));
            // 6 procedural vertices per quad, one draw call for all instances
            pass.draw(0..6, 0..self.instances.len() as u32);
        }
    }

    pub fn resize(&mut self, width: f32, height: f32) {
        self.screen_width = width;
        self.screen_height = height;
        self.ndc_scale_x = 2.0 / width;
        self.ndc_scale_y = 2.0 / height;
    }
}
